project:
  type: book

book:
  title: "Sistemas Inteligentes e Mineração de Dados"
  subtitle: "2ª Edição: Do Weka ao Python"
  author: "José Artur Quilici-Gonzalez, Francisco de Assis Zampirolli e Fábio Rezende de Souza"
  date: "today"
  chapters:
    - index.qmd
    - cap01/cap01.ipynb
    - cap02/cap02.ipynb
    - cap03/cap03.ipynb
    - cap04/cap04.ipynb
    - cap05/cap05.ipynb
    - cap06/cap06.ipynb

lang: pt-BR

bibliography: references.bib
csl: abnt.csl         

format:
  html:
    theme: cosmo
    cite-method: citeproc
    code-tools: true
    toc: true
  pdf:
    cite-method: biblatex
    biblatexoptions: 
      - style=abnt          # ← pacote biblatex-abnt (requer instalação)
      - refsection=chapter  # Refs separadas por capítulo
      - defernumbers=true   # Numera refs por capítulo
    documentclass: report
    number-sections: true
    toc: true
    lof: true
    lot: true
    geometry:
      - top=15mm
      - bottom=20mm
      - left=20mm
      - right=20mm
    include-in-header:
      text: |
          \usepackage{etoolbox}
          \usepackage{titlesec}
          \usepackage{xcolor}
          \usepackage{wallpaper}

          \definecolor{darkblue}{RGB}{0, 51, 102}

          % Estilo dos Capítulos
          \titleformat{\chapter}[display]
            {\normalfont\huge\bfseries\color{darkblue}}
            {\filleft\Large\chaptertitlename\ \thechapter}
            {1ex}
            {\titlerule\vspace{2ex}\Huge\filleft}
            [\vspace{2ex}]
          \titlespacing*{\chapter}{0pt}{5pt}{20pt}

          % REMOVER o capítulo "Bibliography" do final
          \defbibheading{bibliography}{}

          \renewcommand{\maketitle}{%
            \begin{titlepage}
              \ThisCenterWallPaper{1.02}{images/capa.png}
              \vspace*{1cm}
              \begin{flushright}
                {\Huge\bfseries\color{white} Sistemas Inteligentes e Mineração de Dados}\\[0.5cm]
                {\Large\bfseries\color{white} 2ª Edição: Do Weka ao Python}\\[2cm]
                \vfill
                {\large\bfseries\color{white} José Artur Quilici-Gonzalez}\\
                {\large\bfseries\color{white} Francisco de Assis Zampirolli}\\
                {\large\bfseries\color{white} Fábio Rezende de Souza}\\[1cm]
                {\large\color{white} \today}
              \end{flushright}
            \end{titlepage}
            \clearpage
          }
